In [1]:
import pandas as pd
import numpy as np

In [2]:
pat_data = pd.read_excel('Train_dataset.xlsx', sheet_name='Diuresis_TS')
pat_data

,people_ID,2020-03-20 00:00:00,2020-03-21 00:00:00,2020-03-22 00:00:00,2020-03-23 00:00:00,2020-03-24 00:00:00,2020-03-25 00:00:00,2020-03-26 00:00:00
0,1,441,544.2,669.64,821.368,1002.2416,1215.68992,1472.627904
1,2,151,197.2,253.24,321.688,399.9256,492.91072,606.892864
2,3,416,515.2,632.44,776.728,947.7736,1150.32832,1395.793984
3,4,410,506.0,621.40,761.880,928.1560,1126.78720,1368.344640
4,5,390,483.0,595.00,730.200,892.8400,1084.40800,1315.889600
5,6,389,480.8,591.16,723.992,882.6904,1072.22848,1301.274176
6,7,322,401.4,497.08,611.096,749.0152,911.81824,1110.381888
7,8,194,246.8,310.36,388.632,482.9584,592.55008,724.860096
8,9,310,385.0,477.40,589.080,720.7960,877.95520,1069.746240
9,10,242,303.4,379.48,469.976,578.7712,707.52544,865.230528
10,11,373,463.6,570.52,702.424,857.7088,1042.25056,1266.100672
11,12,192,245.4,309.88,389.656,482.3872,591.86464,725.637568
12,13,403,497.6,612.52,751.224,917.1688,1113.60256,1352.523072
13,14,120,157.0,203.80,262.360,328.7320,407.47840,503.574080
14,15,382,474.4,583.48,717.976,876.3712,1064.64544,1293.774528
15,16,239,301.8,377.56,470.872,580.7464,709.89568,865.674816
16,17,199,253.8,318.76,398.712,494.1544,605.98528,741.782336
17,18,182,232.4,295.48,372.376,461.6512,566.98144,694.977728
18,19,181,233.2,295.24,372.088,463.1056,568.72672,698.672064
19,20,220,279.0,351.40,439.480,542.1760,663.61120,812.533440
20,21,246,308.2,385.24,480.088,590.9056,722.08672,881.104064
21,22,220,278.0,350.20,436.440,539.4280,660.31360,807.776320
22,23,415,514.0,632.20,776.440,945.6280,1147.75360,1391.904320
23,24,203,258.6,324.52,404.024,500.5288,613.63456,751.761472
24,25,148,190.6,242.92,309.304,386.8648,477.23776,588.085312
25,26,381,473.2,584.44,719.128,877.7536,1066.30432,1293.365184
26,27,251,315.2,392.44,485.528,596.5336,728.84032,888.408384
27,28,185,236.0,299.80,377.560,468.7720,575.52640,704.431680
28,29,365,454.0,560.20,688.440,841.8280,1023.19360,1242.432320
29,30,405,501.0,616.60,754.520,921.1240,1118.34880,1356.618560
...,...,...,...,...,...,...,...,...
10684,22666,411,508.2,626.44,769.528,940.0336,1141.04032,1384.648384
10685,22667,124,163.8,213.16,271.992,342.9904,424.58848,524.106176
10686,22668,302,376.4,467.08,576.696,707.7352,862.28224,1048.538688
10687,22669,426,526.2,646.84,792.408,966.5896,1172.90752,1423.689024
10688,22670,395,487.0,601.00,735.800,896.8600,1089.23200,1323.278400
10689,22671,388,481.6,594.52,728.024,889.3288,1080.19456,1312.433472
10690,22672,149,192.8,245.56,312.472,390.6664,481.79968,594.359616
10691,22673,418,515.6,634.12,775.544,944.5528,1146.46336,1391.956032
10692,22674,234,295.8,369.16,460.792,568.6504,695.38048,848.256576
10693,22675,159,203.8,261.16,329.592,411.2104,506.45248,621.542976
10694,22676,431,532.2,652.84,798.008,973.3096,1180.97152,1432.565824
10695,22677,248,312.6,391.72,487.864,602.0368,735.44416,896.332992
10696,22678,145,187.0,238.60,304.120,379.7440,468.69280,577.031360
10697,22679,218,274.6,344.92,428.504,529.9048,648.88576,794.062912
10698,22680,372,461.4,570.28,698.936,853.5232,1037.22784,1260.873408
10699,22681,347,430.4,530.68,651.416,795.5992,967.71904,1175.862848
10700,22682,379,467.8,576.76,708.312,863.8744,1049.64928,1273.379136
10701,22683,256,320.2,399.64,497.368,612.5416,748.04992,913.859904
10702,22684,417,515.4,632.68,777.016,949.0192,1151.82304,1397.587648
10703,22685,389,479.8,589.96,722.552,881.8624,1071.23488,1300.881856
10704,22686,339,420.8,519.16,639.192,780.9304,950.11648,1153.939776
10705,22687,241,305.2,382.84,477.208,588.3496,719.01952,878.223424
10706,22688,183,232.6,293.32,368.184,458.4208,563.10496,690.325952
10707,22689,297,370.4,459.88,568.056,698.2672,850.92064,1034.904768
10708,22690,397,489.4,603.88,742.456,906.6472,1100.97664,1337.371968
10709,22691,134,173.8,225.16,287.992,359.4904,444.38848,549.466176
10710,22692,387,479.4,591.88,724.856,884.6272,1074.55264,1303.263168
10711,22693,177,228.4,288.28,362.136,448.4632,551.15584,676.787008
10712,22694,352,438.4,542.68,665.816,814.6792,990.61504,1204.138048
10713,22695,181,230.2,290.44,366.328,455.2936,559.35232,686.622784

In [3]:
pat_trans = pat_data.T

In [4]:
pat_trans.head()

,0,1,2,3,4,5,6,7,8,9,...,10704,10705,10706,10707,10708,10709,10710,10711,10712,10713
people_ID,1.000,2.000,3.000,4.00,5.0,6.000,7.000,8.000,9.00,10.000,...,22686.000,22687.000,22688.000,22689.000,22690.000,22691.000,22692.000,22693.000,22694.000,22695.000
2020-03-20 00:00:00,441.000,151.000,416.000,410.00,390.0,389.000,322.000,194.000,310.00,242.000,...,339.000,241.000,183.000,297.000,397.000,134.000,387.000,177.000,352.000,181.000
2020-03-21 00:00:00,544.200,197.200,515.200,506.00,483.0,480.800,401.400,246.800,385.00,303.400,...,420.800,305.200,232.600,370.400,489.400,173.800,479.400,228.400,438.400,230.200
2020-03-22 00:00:00,669.640,253.240,632.440,621.40,595.0,591.160,497.080,310.360,477.40,379.480,...,519.160,382.840,293.320,459.880,603.880,225.160,591.880,288.280,542.680,290.440
2020-03-23 00:00:00,821.368,321.688,776.728,761.88,730.2,723.992,611.096,388.632,589.08,469.976,...,639.192,477.208,368.184,568.056,742.456,287.992,724.856,362.136,665.816,366.328

In [5]:
pat_trans.columns=pat_trans.columns.values.tolist()
pat_trans

,0,1,2,3,4,5,6,7,8,9,...,10704,10705,10706,10707,10708,10709,10710,10711,10712,10713
people_ID,1.000000,2.000000,3.000000,4.00000,5.0000,6.000000,7.000000,8.000000,9.00000,10.000000,...,22686.000000,22687.000000,22688.000000,22689.000000,22690.000000,22691.000000,22692.000000,22693.000000,22694.000000,22695.000000
2020-03-20 00:00:00,441.000000,151.000000,416.000000,410.00000,390.0000,389.000000,322.000000,194.000000,310.00000,242.000000,...,339.000000,241.000000,183.000000,297.000000,397.000000,134.000000,387.000000,177.000000,352.000000,181.000000
2020-03-21 00:00:00,544.200000,197.200000,515.200000,506.00000,483.0000,480.800000,401.400000,246.800000,385.00000,303.400000,...,420.800000,305.200000,232.600000,370.400000,489.400000,173.800000,479.400000,228.400000,438.400000,230.200000
2020-03-22 00:00:00,669.640000,253.240000,632.440000,621.40000,595.0000,591.160000,497.080000,310.360000,477.40000,379.480000,...,519.160000,382.840000,293.320000,459.880000,603.880000,225.160000,591.880000,288.280000,542.680000,290.440000
2020-03-23 00:00:00,821.368000,321.688000,776.728000,761.88000,730.2000,723.992000,611.096000,388.632000,589.08000,469.976000,...,639.192000,477.208000,368.184000,568.056000,742.456000,287.992000,724.856000,362.136000,665.816000,366.328000
2020-03-24 00:00:00,1002.241600,399.925600,947.773600,928.15600,892.8400,882.690400,749.015200,482.958400,720.79600,578.771200,...,780.930400,588.349600,458.420800,698.267200,906.647200,359.490400,884.627200,448.463200,814.679200,455.293600
2020-03-25 00:00:00,1215.689920,492.910720,1150.328320,1126.78720,1084.4080,1072.228480,911.818240,592.550080,877.95520,707.525440,...,950.116480,719.019520,563.104960,850.920640,1100.976640,444.388480,1074.552640,551.155840,990.615040,559.352320
2020-03-26 00:00:00,1472.627904,606.892864,1395.793984,1368.34464,1315.8896,1301.274176,1110.381888,724.860096,1069.74624,865.230528,...,1153.939776,878.223424,690.325952,1034.904768,1337.371968,549.466176,1303.263168,676.787008,1204.138048,686.622784

In [6]:
pat_trans=np.array(pat_trans)
pat_trans

array([[1.00000000e+00, 2.00000000e+00, 3.00000000e+00, ...,
        2.26930000e+04, 2.26940000e+04, 2.26950000e+04],
       [4.41000000e+02, 1.51000000e+02, 4.16000000e+02, ...,
        1.77000000e+02, 3.52000000e+02, 1.81000000e+02],
       [5.44200000e+02, 1.97200000e+02, 5.15200000e+02, ...,
        2.28400000e+02, 4.38400000e+02, 2.30200000e+02],
       ...,
       [1.00224160e+03, 3.99925600e+02, 9.47773600e+02, ...,
        4.48463200e+02, 8.14679200e+02, 4.55293600e+02],
       [1.21568992e+03, 4.92910720e+02, 1.15032832e+03, ...,
        5.51155840e+02, 9.90615040e+02, 5.59352320e+02],
       [1.47262790e+03, 6.06892864e+02, 1.39579398e+03, ...,
        6.76787008e+02, 1.20413805e+03, 6.86622784e+02]])

In [ ]:
from statsmodels.tsa.vector_ar.var_model import VAR
diu_calc=[]
model = VAR(endog=pat_trans)
model_fit = model.fit()
yhat = model_fit.forecast(model_fit.y, steps=1)
diu_calc.append(yhat)

In [ ]:
len(diu_calc)

In [ ]:
diu_calc

In [ ]:
diu_calc = [j for i in diu_calc for j in i]
print(diu_calc)
print(len(diu_calc))
diu_calc = [j for i in diu_calc for j in i]

In [ ]:
len(diu_calc)

In [ ]:
df=pd.DataFrame(diu_calc, columns=['Diuresis'])

In [ ]:
df

In [ ]:
pat_train=pd.read_excel('Train_dataset.xlsx',sheet_name='Train_dataset')

In [ ]:
pat_train['Diuresis']=df['Diuresis']

In [ ]:
pat_train.drop('Infect_Prob',inplace=True,axis=1)
pat_train

In [ ]:
pat_train.shape

In [ ]:
pat_train.to_excel('new_train_data.xlsx', index=False)

In [ ]:
pat_train=pd.read_excel("Train_dataset.xlsx",sheet_name='Train_dataset')

In [ ]:
pat_train_new=pat_train.drop(['Designation','Name','Insurance','salary'],axis='columns')

In [ ]:
ind=pat_train_new.select_dtypes(include=['object']).columns 
ind

In [ ]:
ind_num=pat_train_new.select_dtypes(include=['int64','float64']).columns
ind_num

In [ ]:
for i in ind:
    pat_train_new=pat_train_new[pat_train_new[i].notna()]
for i in ind_num:
    if i!='people_ID' and i!='Infect_Prob':
        pat_train_new[i].fillna(pat_train_new[i].mean(),inplace=True)
for i in ind:
    pat_train_new[i] = pat_train_new[i].astype('category').cat.codes

In [ ]:
pat_train_new.isna().sum()

In [ ]:
target=pat_train_new['Infect_Prob']
features=pat_train_new.drop(columns=['Infect_Prob'])

In [ ]:
from sklearn.model_selection  import train_test_split
x_train, x_test, y_train, y_test = train_test_split(features, target, random_state=42, test_size=.2)

In [ ]:
from sklearn import linear_model
from sklearn.metrics import mean_squared_error
lr = linear_model.LinearRegression()
model = lr.fit(x_train, y_train)
pred = model.predict(x_test)

In [ ]:
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import r2_score
train_pred=lr.predict(x_test)
print('Testing error_RootMeanSquareError', np.sqrt(mean_squared_error(y_test,train_pred)))

In [ ]:
pat_test=pd.read_excel('new_train_data.xlsx')

In [ ]:
pat_test.columns

In [ ]:
ind_num=pat_test.select_dtypes(include=['int64','float64']).columns
ind_num

In [ ]:
for i in ind:
    pat_test[i].fillna(pat_test[i].value_counts().index[0],inplace=True)
for i in ind_num:
    if i!='people_ID':
        pat_test[i].fillna(pat_test[i].mean(),inplace=True)
for i in ind:
    pat_test[i] = pat_test[i].astype('category').cat.codes
pat_test=pat_test.drop(['Name','Designation','salary','Insurance'],axis=1)

In [ ]:
res_id=pat_test['people_ID']
res_data=pat_test

In [ ]:
res_data.isna().sum()

In [ ]:
pat_test.shape

In [ ]:
'''linear regressor'''
pat_test['Infect_prob']=lr.predict(res_data)

In [ ]:
result=pd.DataFrame({'people_ID':res_id, 'Infect_prob':pat_test['Infect_prob']})
result.to_csv('result_p2.csv', index=False)